version: "3.1"
# The server profiles used in this example are intended for use with edge versions of the product image only.

services:
  pingdirectory:
    image: pingidentity/pingdirectory:latest
    environment:
      - PING_IDENTITY_ACCEPT_EULA=YES
      - SERVER_PROFILE_URL=https://github.com/aurelien-ping/layered_profiles.git
      - SERVER_PROFILE_PATH=getting-started/pingdirectory
      #- SERVER_PROFILE_PARENT=LICENSE
      - MAX_HEAP_SIZE=768m

      #- SERVER_PROFILE_LICENSE_URL=https://github.com/aurelien-ping/layered_profiles.git
      #- SERVER_PROFILE_LICENSE_PATH=license/pingdirectory
    ports:
      - 1636-1646:636
      - 1443-1453:443
    networks:
      - pingnet
  
  pingfederate:
    image: pingidentity/pingfederate:edge
    command: wait-for pingdirectory:389 -t 300 -- entrypoint.sh start-server
    environment:
      - PING_IDENTITY_ACCEPT_EULA=YES
      - SERVER_PROFILE_URL=https://github.com/aurelien-ping/layered_profiles.git
      - SERVER_PROFILE_PATH=getting-started/pingfederate
      #- SERVER_PROFILE_PARENT=LICENSE

      #- SERVER_PROFILE_LICENSE_URL=https://github.com/aurelien-ping/layered_profiles.git
      #- SERVER_PROFILE_LICENSE_PATH=license/pingfederate
    ports:
      - 9031:9031
      - 9999:9999
    networks:
      - pingnet

  pingdataconsole:
    image: pingidentity/pingdataconsole:edge
    ports:
      - 8443:8443
    networks: 
      - pingnet
              
networks:
    pingnet:
